{% set name = "ppscore" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f81f17007e23b917f54295689c8dee8a344206d2f16e5587d85e1c36395437e6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pandas
    - scikit-learn


test:
  requires:
    - python {{ python_min }}
  imports:
    - ppscore

about:
  home: https://github.com/8080labs/ppscore
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python implementation of the Predictive Power Score (PPS)
  description: The PPS is an asymmetric, data-type-agnostic score that can detect linear or non-linear relationships between two columns.
  doc_url: https://github.com/8080labs/ppscore
  dev_url: https://github.com/8080labs/ppscore

extra:
  recipe-maintainers:
    - aschonfeld
